# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vananch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('imo', models.SmallIntegerField()),
                ('mmsi', models.SmallIntegerField()),
                ('marine_traffic_id', models.SmallIntegerField()),
                ('length', models.SmallIntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('completed_ts', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShipRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.SmallIntegerField(blank=True, null=True)),
                ('speed', models.SmallIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vananch.Ship')),
                ('ship_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vananch.ShipImport')),
            ],
        ),
    ]
