# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vananch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('imo', models.SmallIntegerField()),
                ('mmsi', models.SmallIntegerField()),
                ('marine_traffic_id', models.SmallIntegerField()),
                ('length', models.SmallIntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ts', models.DateTimeField()),
                ('course', models.SmallIntegerField(blank=True, null=True)),
                ('speed', models.SmallIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vananch.Ship')),
            ],
        ),
    ]
